# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BlueStackDFPMediationDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BlueStackDFPMediationDemo
    pod 'BlueStackDFPMediationAdapter', '4.4.8.0'

end

target 'BlueStackDFPMediationDemoObjC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BlueStackDFPMediationDemoObjC
    pod 'BlueStackDFPMediationAdapter', '4.4.8.0'

end
